openapi: 3.0.3
info:
  version: 1.0.0
  title: Budget manager application
servers:
  - url: http://wallet.com
tags:
  - name: Currency
  - name: Transaction
  - name: Account
paths:
  /currency:
    get:
      tags:
        - Currency
      summary: Get all currency
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Currency"
    put:
      tags:
        - Currency
      description: Create or update Currency type
      operationId: crupdateCurrency
      summary: Create or update currency
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Currency"
                - type: array
                  items:
                    $ref: "#/components/schemas/Currency"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Currency"
                  - type: array
                    items:
                      $ref: "#/components/schemas/Currency"
components:
  schemas:
    Currency:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Transactions:
      type: object
      properties:
        id:
          type : string
        value:
          type: string
        description:
          type : string
        id_acount:
          type: string
        transaction_date :
          type: string
          format: date


    Accounts:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        id_currency:
          type: string