openapi: 3.0.3
info:
  version: 1.0.0
  title: Budget manager application
servers:
  - url: http://localhost
paths:
  /currency:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Currency"
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/Currency"
                - type: array
                  items:
                    $ref: "#/components/schemas/Currency"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Currency"
                  - type: array
                    items:
                      $ref: "#/components/schemas/Currency"
components:
  schemas:
    Currency:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string